version: '3.9'

services:
  convert_docs_to_images:
    container_name: convert_docs_to_images
    build:
      context: .
      dockerfile: Dockerfile
      args:
        environment: prod
    restart: unless-stopped
    environment:
      - ENVIRONMENT=prod
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
